### ISSUE TITLE
Walking on the rail and damage from the rail.

### ISSUE THREAD

**Issue by BuiuAlves** [H4v0c21/DKC-2-Project-Kongs#73] opened 2023-05-12 15:36 UTC
The bug occurs in the Haunted Hall phase... at the beginning everything is fine, but if you get another kong barrel, the partner doesn't stay in the cart, he just follows you walking on the tracks. Another bug I found was one that deals damage, I was playing with Donkey Kong when I jumped from the hook towards the rail and ended up taking damage from the rail.

**Comment by Mattrizzle** [comment] 2023-05-12 16:50
This is a duplicate of Issues #63 and #64.

**Closed** 2023-05-12 16:54 UTC
